name: default

on: 
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: build&test
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup toolchain
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: build
      run: cargo build --verbose
    - name: test
      run: cargo test --verbose

  build_docker_image:
    name: docker build
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: docker build
        run: docker build -t rust-web-app -f ./docker/Dockerfile .
      - name: docker run container
        run: docker run -p 8080:3000 --rm --name rust-web-app rust-web-app
      - name: health check
        run: curl http://localhost:8000/health